# Generated by Django 3.2.5 on 2021-12-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='cocktail',
            options={'ordering': ('title',), 'verbose_name': 'Коктели', 'verbose_name_plural': 'Коктели'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('title',), 'verbose_name': 'Ингредиенты', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
