# Generated by Django 3.2.5 on 2022-01-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211228_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(height_field=100, upload_to='media/ingredient/', width_field=100),
        ),
    ]
