# Generated by Django 3.2.5 on 2022-02-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_ingredient_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='cocktail',
            options={'ordering': ('title',), 'verbose_name': 'Cocktail', 'verbose_name_plural': 'Cocktails'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('title',), 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
    ]
